<?php

namespace AppBundle\Repository;

/**
 * ApiResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
