<?php

namespace AppBundle\Repository;

/**
 * FileMetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileMetaDataRepository extends \Doctrine\ORM\EntityRepository
{
}
